-- DATA LOGGING: Course Attempts
create table course_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  
  course_id text not null,
  day_id integer not null,
  
  score integer not null,
  total_questions integer not null,
  accuracy numeric(5,2), -- e.g. 95.50
  time_taken integer, -- in seconds
  passed boolean default false
);

-- RLS
alter table course_attempts enable row level security;

create policy "Users can view own course attempts." on course_attempts
  for select using ((select auth.uid()) = user_id);

create policy "Users can insert own course attempts." on course_attempts
  for insert with check ((select auth.uid()) = user_id);
