 -- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security!
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- This triggers a profile creation when a new user signs up via Supabase Auth
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();



-- DAILY PROGRESS TABLE
create table daily_progress (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  course_id text not null, -- 'speed-maths'
  day_id integer not null, -- 1, 2, 3...
  
  -- Step Completion Status
  video_watched boolean default false,
  notes_read boolean default false,
  practice_score integer default 0, -- 0-100%
  compete_score integer default 0,
  
  is_complete boolean default false, -- True if daily goal is met

  unique(user_id, course_id, day_id) -- One entry per day per course per user
);

alter table daily_progress enable row level security;

create policy "Users can view own progress." on daily_progress
  for select using ((select auth.uid()) = user_id);

create policy "Users can update own progress." on daily_progress
  for insert with check ((select auth.uid()) = user_id);

create policy "Users can update own progress rows." on daily_progress
  for update using ((select auth.uid()) = user_id);
