-- 1. Create the table if it doesn't exist
CREATE TABLE IF NOT EXISTS course_attempts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) on delete cascade not null, -- Fixed reference to auth.users
  
  course_id text not null,
  day_id integer not null,
  task_id text, -- Added task_id directly
  
  score integer not null,
  total_questions integer not null,
  accuracy numeric(5,2),
  time_taken integer,
  passed boolean default false
);

-- 2. Enable RLS
ALTER TABLE course_attempts ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies (Drop first to avoid errors if re-running)
DROP POLICY IF EXISTS "Users can view own course attempts." ON course_attempts;
CREATE POLICY "Users can view own course attempts." ON course_attempts
  FOR SELECT USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "Users can insert own course attempts." ON course_attempts;
CREATE POLICY "Users can insert own course attempts." ON course_attempts
  FOR INSERT WITH CHECK ((select auth.uid()) = user_id);

-- 4. Create Index
CREATE INDEX IF NOT EXISTS idx_course_attempts_task ON course_attempts(course_id, day_id, task_id);
