-- Create flashcard_reviews table
create table if not exists flashcard_reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  course_id text not null,
  card_id text not null,
  front text not null,
  back text not null,
  unique(user_id, course_id, card_id)
);

-- Enable RLS
alter table flashcard_reviews enable row level security;

-- Policies
create policy "Users can view own reviews"
  on flashcard_reviews for select
  using ( auth.uid() = user_id );

create policy "Users can insert own reviews"
  on flashcard_reviews for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete own reviews"
  on flashcard_reviews for delete
  using ( auth.uid() = user_id );
